### ISSUE TITLE
Referring in Bevy Assets

### ISSUE THREAD

**Issue by RuelYasa** [laundmo/bevy-spatial#33]
Sorry for bothering. This project has helped me a lot recently,  but it was hard to find the project, partly because that it isn't referred in Bevy Assets. Therefore, I wonder if you want to mention the project there, which can help others discovering this nice project.

If so, this might be what you need:
``` toml
name = "bevy-spatial"
description = "A plugin to track your entities in spatial indices and query them."
link = "https://github.com/laundmo/bevy-spatial"
```
,and I suppose it be in "Helpers" category.

Also, it would be great if you could add an image to showcase the project by adding
``` toml
image = "bevy-spatial.png"
```
 and placing `bevy-spatial.png`  near your toml file.

Thanks for your consideration!
